language: python

branches:
  only:
    - /^v0\.5.*$/

python:
  - '2.7'

# Setup anaconda
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libgdal1h gdal-bin libgdal-dev libcurl4-gnutls-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib gdal scikit-image requests six nose dateutil
  - pip install --install-option="--no-cython-compile" cython
  - pip install -r requirements/travis.txt

script:
  - nosetests

after_success:
  - coveralls
